services:
  redis:
    image: redis:6.2-alpine
    ports:
      - '${REDIS_PORT}:6379'
  web:
    build:
      context: .
    stop_signal: SIGINT
    ports:
      - '${API_PORT}:8080'
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    depends_on:
      - redis
    command: [ "poetry", "run", "gunicorn", "-w", "${GUNICORN_WORKERS}", "-b", "0.0.0.0:8080", "wsgi:app" ]